version: '3'

services:

  # LIFECYCLE
  lifecycle:
    image: mf2c/lifecycle
    expose:
      - "46000"
    ports:
      - "46000:46000"
    environment:
      - CIMI_URL=https://dashboard.mf2c-project.eu/api
      - HOST_IP=192.168.252.41
      - WORKING_DIR_VOLUME=/tmp/compose_files
      - URL_PM_SLA_MANAGER=http://slalite:46030
      - URL_AC_SERVICE_MNGMT=http://service-manager:46200/api/service-management
    volumes:
      - /tmp/compose_files:/tmp/compose_files
      - /var/run/docker.sock:/var/run/docker.sock

  # USER MANAGEMENT
  user-management:
    image: mf2c/user-management
    expose:
      - "46300"
    ports:
      - "46300:46300"
    environment:
      - CIMI_URL=https://dashboard.mf2c-project.eu/api

  # SLA MANAGER

